# RIT IMGS 211: Probability and Statistics for Imaging Scientists
### Created by Gabriel J. Diaz

...but portions of this homework were taken and/or adapted from this [github repo provided by Franck Iutzeler of U. Grenoble](https://github.com/iutzeler/Introduction-to-Python-for-Data-Sciences/blob/master/1_Basics.ipynb).

# 1. Code and text cells using keyboard shortcuts.

First things first.  There are "code" cells, and "text" cells. This is a text cell.

Mouse-over the boundary betwen cells and you will see the option to create a cell of either type.

...or better yet, do it using your keyboard!  Keyboard shortcuts will make your life much easier.  They may vary between mac/pc, so click on "Tools" in the menu bar and select "Keyboard shortcuts."   Find the shortcut for "insert code cell below."  for me, it's ctrl-m, then b.

Note that you can also use the Tools menu to change the shortcut scheme to two other modes:  VIM and classic.

# 2. Numerical types

Variables are weakly typed in python which means that their type is deduced from the context: the initialization or the types of the variables used for its computation. In the following example, I create some integers and floats.  You can examine a variables type using "type()".

In [ ]:
print("Integer")
a = 3
print(a,type(a))

print("\nFloat")
b = 3.14
print(b,type(b))

print("\nComplex")
c = 3.14 + 2j
print(c,type(c))
print(c.real,type(c.real))
print(c.imag,type(c.imag))

Integer
3 <class 'int'>

Float
3.14 <class 'float'>

Complex
(3.14+2j) <class 'complex'>
3.14 <class 'float'>
2.0 <class 'float'>

# 3. Basic String and Print Operations

In this section, we aim to familiarize you with basic string handling in Python. String manipulation is an essential skill as strings are one of the most common types of data that you will encounter in programming.

### String concatenation

Strings can be added together using the + operator. This is known as string concatenation. Now, you are going to create two strings and combine them.

In [18]:
string1 = "rochester insti"
string2 = "tute"

print(string1 + string2)

string3 = "of technology"

# Below, notice that I create an temporary or "anonymous
# string inline, which is just a space: " "
# it is "anonymous" in that the string is never assigned to a variable.
print(string1 + string2 + " " + string3)

rochester institute
rochester institute of technology

You can also include numbers in a string, but this requires that you first convert them to a string.  You can do this by wrapping the number in str().

In [19]:
print( str(1) + " is the loneliest number you will everrr dooooo....")

pi = 3.14159265358979323846264338327950288419716939937510582

print("Simple printing doesn't afford control over numerical precision.  For example, pi is " + str(pi) )

1 is the loneliest number you will everrr dooooo....
Simple printing doesn't afford control over numerical precision.  For example, pi is 3.141592653589793

### Control the precision of printed numbers

Notice that the print statement above prints a seemingly arbitrary number of values after the decimal.

Yes, there is a default setting for this that you can change, but there is a better way.

You can use print() in combination with an f-string, which I demonstrate below.  

You can learn more about f-strings here:
https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/

In [51]:
blargh = 1.12345

print(f'Blargh is: {blargh}')
print(f'Blargh is: {blargh:.1f}') # One value of precision
print(f'Blargh is: {blargh:.2f}') # Two values of precision
print(f'Blargh is: {blargh:.3f}') # Three values of precision

Blargh is: 1.12345
Blargh is: 1.1
Blargh is: 1.12
Blargh is: 1.123
There are 10 cookies in the cookies jar, which is 0.45 percent of the original amount.

Here is a more complicated string that includes ints, strings, and formatted floats.

In [59]:

hotdogs_in_package = 8
buns_in_package = 6
a_string = "hot dogs"
another_string = "buns"


print( f'There are {hotdogs_in_package} {a_string} in a package, and {buns_in_package} {another_string} in a package.' )
print( f'The bun-to-hotdog ratio is {buns_in_package/hotdogs_in_package:.2f}.  Why would anyone would do this!?!')

There are 8 hot dogs in a package, and 6 buns in a package.
The bun-to-hotdog ratio is 0.75.  Why would anyone would do this!?!

# Boolean comparisons

Both numbers and strings can be compared using operators basic "bollean" operators.

In [ ]:
# the 2>1  after the comma is the comparison or "boolean operation" that asks, "Is 2 > 1?"
print('2 > 1?', 2 > 1)

2 > 1? True

In [ ]:
# Some more examples:

print('2 > 2?', 2 > 2)
print('2 >= 2?',2 >= 2)
print('2 == 2?',2 == 2)
print('2 == 2.0?',2 == 2.0)
print('2 != 1.9?',2 != 1.9)

2 > 2? False
2 >= 2? True
2 == 2? True
2 == 2.0? True
2 != 1.9? True

In [ ]:
# Now, with strings!
print('apple == orange?', 'apple' == 'orange')
print('apple == apple?' , 'apple' == 'apple')

apple == orange? False
apple == apple? True

## Booleans

Boolean is the type of a variable `True` or `False` and thus are extremely useful when coding.
* They can be obtained by comparisons  `>`, `>=` (greater, greater or equal), `<`, `<=` (smaller, smaller or equal) or membership `==` , `!=` (equality, different).
* They can be manipulated by the logical operations `and`, `not`, `or`.

In [ ]:
print('2 > 1\t', 2 > 1)
print('2 > 2\t', 2 > 2)
print('2 >= 2\t',2 >= 2)
print('2 == 2\t',2 == 2)
print('2 == 2.0',2 == 2.0)
print('2 != 1.9',2 != 1.9)

2 > 1	 True
2 > 2	 False
2 >= 2	 True
2 == 2	 True
2 == 2.0 True
2 != 1.9 True

# Lists, slicing, and iteration

Lists are the base element for sequences of variables in python, they are themselves a variable type.  

The syntax to create a list is `[ ... , ... ]`

*Warning:* Another type called *tuple* with the syntax `( ... , ... )` exists in Python. It has almost the same structure than list to the notable exceptions that one cannot add or remove elements from a tuple. We will run into them eventually, but for now, don't worry about them.

In [ ]:
l = [1, 2, 3, 4, 5]
print( type(l))
print(l)

<class 'list'>
[1, 2, 3, 4, 5]

Lists can be of any type.  They can even contain multiple types!

In [ ]:
list_of_strings = ['thurston', 'kim', 'lee', 'steve']
print(list_of_strings)

a_mixed_type_list = ['1', 'elephant', '3.5', ['10', '20']] # the last element is a list nested within a_mixed_type_list.
print(a_mixed_type_list)

['thurston', 'kim', 'lee', 'steve']
['1', 'elephant', '3.5', ['10', '20']]

Indexing into a list is done using brackets.  Indices begin with 0.

In [ ]:
l = [1, 2, 3, 4, 5]
print( l[0] )
print( l[1] )

1
2

A negative index implies a position relative to the end of the list.

In [ ]:
l = [1, 2, 3, 4, 5]
print( l[-1] )
print( l[-2] )

5
4

You can access a "slice" of a list (ie., several consecutive indices using a colon.

In [ ]:
l = [1, 2, 3, 4, 5]
print( l[1:3] )

[2, 3]

### Operations on lists

One can add, insert, remove, count, or test if a element is in a list easily

In [ ]:
l = [1, 2, 3, 4, 5]
l.append(10)   # Add an element to l (the list is not copied, it is actually l that is modified)
print(l)

[1, 2, 3, 4, 5, 10]

Use len() to find the length of a list.

In [ ]:
l = [1, 2, 3, 4, 5]
print(len(l)) # length of a list

5

# Iteration through list-like objects using a for loop (iterables)

To iterate means to move through a list-like variable element by element.  Things that can be iterated are referred to as "iterable." Here are a few methods for interation using the *for* loop.

Note that in Python, the contents of a for loop require indentation of *one tab*.  **The indentation is primordial and at the core of Python.**

In [20]:
list_of_strings = ['alpha', 'beta', 'gamma', 'delta']

for i in list_of_strings:
  print(i)

alpha
beta
gamma
delta

You can use the range() function to index into specific values.  Below, we demonstrate how the variable x is controlled using for() and range().

Note that the start value is included in the range, but the stop value is excluded.

In [ ]:
print("Range (from 0) to 4 (excluded) ")
for x in range(4):
    print(x)

print("Range from 2 (included) to 6 (excluded) ")
for x in range(2,6):
    print(x)

print("Range from 1 (included) to 12 (excluded) by steps of 3 ")
for x in range(1,12,3):
    print(x)

Range (from 0) to 4 (excluded)
0
1
2
3
Range from 2 (included) to 6 (excluded)
2
3
4
5
Range from 1 (included) to 12 (excluded) by steps of 3
1
4
7
10

Now, we will use for() and range() to index into a list.

In [22]:
a_list = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']

print('Even numbers:')
for i in range(0,10,2): # from 0 to 10 in steps of 2
  print( a_list[i])

print('\nEvery third number:') # \n is a linebreak!
for i in range(0,10,3):
  print( a_list[i])

Even numbers:
zero
two
four
six
eight

Every third number:
zero
three
six
nine

### Need to keep track of where you are when iterating through a list?  There are at least two ways.

1) Assign a count variable that is incremented within the for loop.

2) You can use enumerate(). At each iteration/step through the list, enumerate() assigns both its index location in the list and the value at location.

In [34]:
a_list = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']


print("Using a variable counter:")
count = 0;
for value in a_list: # note that the variable name "value" could be any other name.
  print(str(count) + ": " +value )
  count = count +1

# Again, "index" and "value" are arbitrary variable names, but the index will always be the first and the value the second
print("\nUsing enumerate():")
for index, value in enumerate(a_list):
  print(str(index) + ": " +value )

# Let me demonstrate the arbitray nature of those variable names.
# All that matters is that the index is assigned to the first variable, and the value to the second.
print("\nUsing enumerate() and different variable names:")
for chicken, cow in enumerate(a_list):
  print(str(chicken) + ": " +cow )

Using a variable counter:
0: zero
1: one
2: two
3: three
4: four
5: five
6: six
7: seven
8: eight
9: nine

Using enumerate():
0: zero
1: one
2: two
3: three
4: four
5: five
6: six
7: seven
8: eight
9: nine

Using enumerate() and different variable names:
0: zero
1: one
2: two
3: three
4: four
5: five
6: six
7: seven
8: eight
9: nine

You can also use build a list within a for loop!

In [ ]:
# first, initialize an empty list
a_list = []

for i in range(0,100,10):
  a_list.append(i)

print(a_list) # notice that it stops at 90!

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
a_list = []

for i in range(0,101,10): # only this line is different from the last cell
  a_list.append(i)

print(a_list)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

Now, with a string.

In [ ]:
sentence = ""
for word in ["Python", "for", "data", "Science"]:
    sentence = sentence + word + " "
print(sentence)

Python for data Science


## If, Elif, Else

In [ ]:
statement1 = False
statement2 = False

if statement1:
    print("statement1 is True")
elif statement2:
    print("statement2 is True")
else:
    print("statement1 and statement2 are False")

statement1 and statement2 are False

In [ ]:
# This is assigning statement 1 to statement 2
statement1 = statement2 = True

if statement1:
    if statement2:
        print("both statement1 and statement2 are True")

both statement1 and statement2 are True

You can also use boolean operators to compare two items.  

Let's demonstrate this by comparing integers.

In [40]:


a = 1
b = 2

if a > b:
  print(f"{a} is greater than {b}")
else:
  print(f"{b} is greater than {a}")

2 is greater than 1

### Now, with strings

In [41]:


a = 'moop'
b = 'boop'
c = 'moop'

if a == b:
  print(f"{a} is the same as {b}")
else:
  print(f"{a} is not the same as {b}")

if a == c:
  print(f"{a} is the same as {c}")
else:
  print(f"{a} is not the same as {c}")

moop is not the same as boop
moop is the same as moop

# Custom python Functions

In Python, a function is defined as def function_name(function_arguments): followed by an indentation representing what is inside the function. (No return arguments are provided a priori)

This function prints a message within the function, but does not return a value.

In [ ]:
def my_fun():
    print("You call this fun!??!")

my_fun()

You call this fun!??!

This function returns the string.

In [ ]:
def my_fun():
    return "You call this fun!??!"

print( my_fun() )

You call this fun!??!

Functions can accept arguments in (i.e., argin).
Here, we accept one argin and assign it to the variable "x"

In [ ]:
def square(x):
    return(x * x)

print( square(12) )
print( square(13) )
print( square(14) )

144
169
196

Funtions can be very helpful when automating tasks.

In [ ]:
def in_bedify(string_in):

    if string_in[-1] == '.': # if there the sentence ends in a "."
      string_in = string_in[:-1] # ...get everything but the last char

    string_out = string_in + ' in bed!'
    return string_out

# from http://www.fortunecookiemessage.com/
list_of_fortunes = ['Go confidently in the direction of your dreams.',
                    'Good things come to those who wait',
                    'A wise man once said, everything in its own time and place']

for i in list_of_fortunes:
  print( in_bedify(i) )

Go confidently in the direction of your dreams in bed!
Good things come to those who wait in bed!
A wise man once said, everything in its own time and place in bed!